---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: autoscaler-secret
  namespace: kube-system
data:
  # value should be base64 encoded
  DATACENTER_ID: `{"tokens": ["TOKEN1", "TOKEN2"], "endpoint": "IONOS_ENDPOINT_TO_USE"}`
